name: Update GitHub Profile

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 * * * *"

jobs:
  update-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # ✅ Fixed: Update GitHub Activity (new maintained action)
      - name: Update GitHub Activity
        uses: jamesgeorge007/github-activity-readme@v0.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate GitHub Metrics
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: techy-zenith
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full
          plugin_stars: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          output_action: commit
          output_path: github-metrics.svg
